"""Markdown formatter for review comments (story-5-3).

Platform-specific formatting with verdict badges, findings tables,
collapsible borderline sections, and progressive truncation.
"""

from __future__ import annotations

import logging
import re
from typing import Literal

from prbot.review.models import AgentError, AgentOutcome, AgentResult
from prbot.review.scorer import ReviewScore, ScoredFinding
from prbot.review.verdict import ReviewVerdict
from prbot.vcs.models import InlineComment, PRDiff

logger = logging.getLogger(__name__)

# Platform comment size limits
_PLATFORM_LIMITS: dict[str, int] = {
    "github": 65536,
    "gitlab": 1_000_000,
}

# Verdict badges
_VERDICT_BADGES: dict[str, str] = {
    "APPROVE": "✅",
    "COMMENT": "💬",
    "REQUEST_CHANGES": "❌",
}

# Severity emoji for findings table
_SEVERITY_EMOJI: dict[str, str] = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🔵",
    "info": "⚪",
}

# Caps on model-supplied fields (B7). One finding must not be able to
# consume the platform comment limit on its own, and a cap makes the
# progressive truncation in truncate_comment a fallback rather than the
# first line of defence.
_MAX_TITLE = 200
_MAX_DESCRIPTION = 4000
_MAX_SUGGESTION = 2000
_MAX_PATH = 400

# A mention that would notify a real person. Preceded by a non-word, so an
# email address local part does not qualify.
_MENTION = re.compile(r"(?<![\w`@.-])@([A-Za-z0-9][A-Za-z0-9-]{0,38})\b")

_WHITESPACE = re.compile(r"\s+")

# A URL the model emitted, including the scheme-less "www." form that
# GitHub autolinks on its own.
_URL = re.compile(
    r"(?i)\b(?:(?P<scheme>https?|ftp)://|(?P<www>www\.))"
    r"(?P<rest>[^\s<>`\]\)]*)",
)

# Renders identically, is not a link. Placed after the separator so the
# host stays readable to a person reading the comment.
_ZWSP = "\u200b"


def _defuse_link(match: re.Match[str]) -> str:
    """Break a URL so it renders as text rather than a link."""
    rest = match.group("rest")
    if match.group("scheme"):
        return f"{match.group('scheme')}:/{_ZWSP}/{rest}"
    return f"www.{_ZWSP}{rest}"


def _sanitise(text: str, limit: int) -> str:
    """Neutralise model-supplied text before it enters the comment (B7).

    The four prompt-injection layers all stop at the model boundary. This is
    the other end: prbot posts the model's words with pull-requests: write,
    so those words must not be able to open an HTML element, forge prbot's
    own state marker, or notify people.

    Escaping "<" is enough for all three. Markdown renders "&lt;" as a
    literal "<", so a finding that discusses <script> still reads correctly
    while being unable to open one.
    """
    if not text:
        return ""
    text = text[:limit]
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    # Backtick the handle rather than delete it: the reader still sees who
    # was named, and no notification fires.
    text = _MENTION.sub(r"`@\1`", text)
    # Break the link syntax itself rather than relying on a code span to
    # contain it (SEC-DATA-01). A code span is not containment: a stray
    # backtick anywhere in the model's text closes it, and GitHub autolinks
    # a bare "www." host that has no scheme to wrap in the first place.
    # A zero-width space after the scheme separator, or after "www.", leaves
    # the text readable and stops the autolinker recognising it.
    text = _URL.sub(_defuse_link, text)
    return text.replace("[", "&#91;").replace("]", "&#93;")


def _cell(text: str, limit: int) -> str:
    """Sanitise text for a markdown table cell.

    A pipe ends a cell and a newline ends a row, so either one from the
    model reshapes the table around it.
    """
    flattened = _WHITESPACE.sub(" ", text).strip()
    # The backslash is escaped FIRST. Escaping only the pipe leaves text
    # containing "\\|" as "\\\\|", and a table row is split on pipes before
    # inline parsing, where a backslash consumes the character after it: the
    # first backslash eats the second and the pipe splits the cell anyway
    # (SEC-DATA-02).
    return (
        _sanitise(flattened, limit)
        .replace("\\", "\\\\")
        .replace("|", "\\|")
    )


# Non-determinism disclaimer (S83)
_DISCLAIMER = (
    "_This review was generated by an AI model and may contain errors. "
    "Findings should be verified by a human reviewer._"
)


def format_review_comment(
    verdict: ReviewVerdict,
    score: ReviewScore,
    reported: list[ScoredFinding],
    borderline: list[ScoredFinding],
    hidden_count: int,
    outcomes: list[AgentOutcome],
    state_html: str = "",
    platform: Literal["github", "gitlab"] = "github",
    suppressed_count: int = 0,
    fixed_count: int = 0,
) -> str:
    """Format the full review comment (G-28, S83).

    Handles both-agents-failed case with distinct body.
    """
    has_results = any(isinstance(o, AgentResult) for o in outcomes)

    # G-28: Both agents failed
    if not has_results:
        return _format_review_incomplete(outcomes, state_html)

    sections = [
        _format_header(verdict, score),
        _format_findings_table(reported),
        _format_borderline_section(borderline),
        _format_agent_status(outcomes),
        _format_footer(
            hidden_count, state_html, suppressed_count, fixed_count,
        ),
    ]

    comment = "\n\n".join(s for s in sections if s)
    limit = _PLATFORM_LIMITS.get(platform, 65536)

    if len(comment) > limit:
        comment = truncate_comment(
            comment, limit, borderline, reported,
        )

    return comment


def _format_review_incomplete(
    outcomes: list[AgentOutcome],
    state_html: str,
) -> str:
    """Format body when both agents failed (G-28)."""
    lines = [
        "## ⚠️ Review Incomplete",
        "",
        "Both review agents encountered errors. "
        "No findings could be produced.",
        "",
    ]

    for outcome in outcomes:
        if isinstance(outcome, AgentError):
            lines.append(
                f"- **{outcome.agent}**: {_cell(outcome.error_type, 64)} — "
                f"{_cell(outcome.message, 400)}",
            )

    lines.extend([
        "",
        "---",
        _DISCLAIMER,
    ])

    if state_html:
        lines.extend(["", state_html])

    return "\n".join(lines)


def _format_header(verdict: ReviewVerdict, score: ReviewScore) -> str:
    """Format header with verdict badge and score."""
    badge = _VERDICT_BADGES.get(verdict.value, "")
    override = " _(critical override)_" if score.critical_override else ""
    return (
        f"## {badge} {verdict.value} — Score: "
        f"{score.clamped_score}/100{override}"
    )


def _format_findings_table(reported: list[ScoredFinding]) -> str:
    """Format findings table sorted by severity then confidence."""
    if not reported:
        return "_No findings to report._"

    severity_order = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
    sorted_findings = sorted(
        reported,
        key=lambda sf: (
            severity_order.get(sf.finding.severity, 99),
            -sf.finding.confidence,
        ),
    )

    lines = [
        "### Findings",
        "",
        "| Severity | Check | File | Lines | Confidence | Title |",
        "|----------|-------|------|-------|------------|-------|",
    ]

    for sf in sorted_findings:
        f = sf.finding
        emoji = _SEVERITY_EMOJI.get(f.severity, "")
        agreement = (
            " (both agents)" if len(f.reported_by) > 1 else ""
        )
        lines.append(
            f"| {emoji} {f.severity} | `{_cell(f.check_id, 64)}` | "
            f"`{_cell(f.file_path, _MAX_PATH)}` | "
            f"{f.line_start}-{f.line_end} | "
            f"{f.confidence}% | {_cell(f.title, _MAX_TITLE)}{agreement} |",
        )

    # Add details for each finding
    lines.append("")
    for sf in sorted_findings:
        f = sf.finding
        lines.extend([
            f"#### `{_cell(f.check_id, 64)}`: {_cell(f.title, _MAX_TITLE)}",
            "",
            f"**File:** `{_cell(f.file_path, _MAX_PATH)}` "
            f"(L{f.line_start}-L{f.line_end})",
            "",
            _sanitise(f.description, _MAX_DESCRIPTION),
            "",
        ])
        if f.failure_scenario:
            lines.extend([
                "**How it breaks:** "
                + _sanitise(f.failure_scenario, _MAX_DESCRIPTION),
                "",
            ])
        if f.suggestion:
            lines.extend([
                f"**Suggestion:** {_sanitise(f.suggestion, _MAX_SUGGESTION)}",
                "",
            ])

    return "\n".join(lines)


def _format_borderline_section(
    borderline: list[ScoredFinding],
) -> str:
    """Format borderline findings in collapsed section."""
    if not borderline:
        return ""

    lines = [
        "<details>",
        f"<summary>Borderline findings ({len(borderline)})</summary>",
        "",
    ]

    for sf in borderline:
        f = sf.finding
        emoji = _SEVERITY_EMOJI.get(f.severity, "")
        lines.extend([
            f"- {emoji} **`{_cell(f.check_id, 64)}`**: "
            f"{_cell(f.title, _MAX_TITLE)} "
            f"(`{_cell(f.file_path, _MAX_PATH)}` "
            f"L{f.line_start}-L{f.line_end}, "
            f"{f.confidence}% confidence)",
        ])

    lines.extend(["", "</details>"])
    return "\n".join(lines)


def _format_agent_status(outcomes: list[AgentOutcome]) -> str:
    """Format agent status, aggregated per agent (GEN-ARCH-01).

    A chunked review runs each agent once per chunk, so rendering one bullet
    per outcome showed the same agent several times with unlabelled numbers
    and nothing saying chunking had happened. Figures are summed per agent
    and the number of passes is stated when there was more than one.
    """
    order: list[str] = []
    stats: dict[str, dict[str, object]] = {}

    for outcome in outcomes:
        name = outcome.agent
        if name not in stats:
            order.append(name)
            stats[name] = {
                "passes": 0, "ok": 0, "findings": 0,
                "tokens": 0, "ms": 0, "errors": [],
            }
        s = stats[name]
        s["passes"] = int(s["passes"]) + 1
        if isinstance(outcome, AgentResult):
            s["ok"] = int(s["ok"]) + 1
            s["findings"] = int(s["findings"]) + len(outcome.findings)
            s["tokens"] = int(s["tokens"]) + (
                outcome.token_usage.input_tokens
                + outcome.token_usage.output_tokens
            )
            s["ms"] = int(s["ms"]) + outcome.latency_ms
        elif isinstance(outcome, AgentError):
            retry_note = " (retryable)" if outcome.retryable else ""
            errs = s["errors"]
            assert isinstance(errs, list)
            errs.append(
                f"{_cell(outcome.error_type, 64)}{retry_note} — "
                f"{_cell(outcome.message, 400)}",
            )

    lines = ["### Agent Status", ""]
    for name in order:
        s = stats[name]
        passes, ok = int(s["passes"]), int(s["ok"])
        errors = s["errors"]
        assert isinstance(errors, list)

        if ok == 0:
            # Every error, not just the first (GEN-ERR-02). Three chunks
            # failing three different ways is three different diagnoses, and
            # showing one of them hides the other two.
            lines.append(
                f"- **{name}**: ❌ no successful pass "
                f"({passes} attempted)",
            )
            for err in errors:
                lines.append(f"  - {err}")
            continue

        pass_note = f", {passes} passes" if passes > 1 else ""
        partial = f" ({ok} of {passes} passes succeeded)" if errors else ""
        lines.append(
            f"- **{name}**: {'✅' if not errors else '⚠️'} "
            f"{s['findings']} findings, {s['tokens']} tokens, "
            f"{s['ms']}ms{pass_note}{partial}",
        )
        for err in errors:
            lines.append(f"  - {err}")

    return "\n".join(lines)


def _format_footer(
    hidden_count: int,
    state_html: str,
    suppressed_count: int = 0,
    fixed_count: int = 0,
) -> str:
    """Format footer with metadata, disclaimer, and state record."""
    lines = ["---"]

    if hidden_count > 0:
        lines.append(
            f"_{hidden_count} low-confidence findings hidden._",
        )

    if suppressed_count > 0:
        # Always stated. A suppression list nobody can see stops being a
        # policy and becomes a gag (C4).
        lines.append(
            f"_{suppressed_count} finding(s) suppressed by "
            f"configuration._",
        )

    if fixed_count > 0:
        # C8: progress is worth stating. A review that only ever lists what
        # is wrong reads as a wall that never moves.
        lines.append(
            f"_{fixed_count} finding(s) resolved since the last review._",
        )

    lines.extend(["", _DISCLAIMER])

    if state_html:
        lines.extend(["", state_html])

    return "\n".join(lines)


def truncate_comment(
    comment: str,
    limit: int,
    borderline: list[ScoredFinding],
    reported: list[ScoredFinding],
) -> str:
    """Progressively truncate comment to fit platform limit (S17).

    Truncation order:
    1. Remove borderline section
    2. Remove low-severity finding details
    3. Truncate remaining content, preserving header and footer
    """
    # Step 1: Remove borderline section
    if "<details>" in comment and len(comment) > limit:
        start = comment.find("<details>")
        end = comment.find("</details>")
        if start != -1 and end != -1:
            comment = (
                comment[:start]
                + "_Borderline findings truncated for size._\n"
                + comment[end + len("</details>") :]
            )

    if len(comment) <= limit:
        return comment

    # Step 2: Remove low-severity details (info, low)
    for severity in ("info", "low"):
        for sf in reported:
            if sf.finding.severity == severity:
                detail_header = f"#### `{sf.finding.check_id}`: {sf.finding.title}"
                idx = comment.find(detail_header)
                if idx != -1:
                    next_header = comment.find("####", idx + 1)
                    next_section = comment.find("###", idx + 1)
                    end_pos = min(
                        p for p in (next_header, next_section, len(comment)) if p > idx
                    )
                    comment = comment[:idx] + comment[end_pos:]

        if len(comment) <= limit:
            return comment

    # Step 3: Hard truncate preserving footer
    footer_marker = comment.rfind("---")
    if footer_marker != -1:
        footer = comment[footer_marker:]
        available = limit - len(footer) - 50
        if available > 0:
            comment = (
                comment[:available]
                + "\n\n_...truncated for size..._\n\n"
                + footer
            )

    return comment[:limit]


def build_inline_comments(
    reported: list[ScoredFinding],
    diff: PRDiff,
) -> list[InlineComment]:
    """Turn findings into comments anchored to the lines they are about (C1).

    Only findings that land on a line the diff actually covers become inline.
    Anything else stays in the summary, where it can still be read, rather
    than being anchored to a line the platform would reject or, worse,
    silently move.

    diff_parser has computed these coordinates since the beginning and
    nothing used them.
    """
    from prbot.review.identity import finding_fingerprint, marker_for
    from prbot.security.validation import _build_line_index

    index = _build_line_index(diff)
    comments: list[InlineComment] = []

    for scored in reported:
        f = scored.finding
        covered = index.get(f.file_path)
        if not covered:
            continue
        if f.line_end not in covered:
            continue

        parts = [
            f"**`{_cell(f.check_id, 64)}`** "
            f"({_cell(f.severity, 16)}, {f.confidence}% confidence)",
            "",
            _sanitise(f.description, _MAX_DESCRIPTION),
        ]
        if f.failure_scenario:
            parts += [
                "",
                "**How it breaks:** "
                + _sanitise(f.failure_scenario, _MAX_DESCRIPTION),
            ]
        if f.suggestion:
            parts += [
                "",
                "**Suggestion:** " + _sanitise(f.suggestion, _MAX_SUGGESTION),
            ]

        # C8: the fingerprint makes this thread recognisable on the next
        # run, so the finding is not posted twice and can be closed out when
        # it goes away. Invisible in rendered markdown.
        parts += ["", marker_for(finding_fingerprint(f))]

        start = f.line_start if f.line_start in covered else None
        comments.append(
            InlineComment(
                path=f.file_path,
                line=f.line_end,
                body="\n".join(parts),
                start_line=start if start != f.line_end else None,
            ),
        )

    return comments
