"""Markdown formatter for review comments (story-5-3).

Platform-specific formatting with verdict badges, findings tables,
collapsible borderline sections, and progressive truncation.
"""

from __future__ import annotations

import logging
import re
from typing import Literal

from prbot.review.identity import finding_fingerprint, marker_for
from prbot.review.models import (
    SEVERITY_LEVELS,
    AgentError,
    AgentOutcome,
    AgentResult,
    Finding,
)
from prbot.review.scorer import ReviewScore, ScoredFinding
from prbot.review.verdict import ReviewVerdict
from prbot.vcs.models import InlineComment, PRDiff

logger = logging.getLogger(__name__)

# Platform comment size limits
_PLATFORM_LIMITS: dict[str, int] = {
    "github": 65536,
    "gitlab": 1_000_000,
}

# Verdict badges
_VERDICT_BADGES: dict[str, str] = {
    "APPROVE": "✅",
    "COMMENT": "💬",
    "REQUEST_CHANGES": "❌",
}

# Severity emoji for findings table
_SEVERITY_EMOJI: dict[str, str] = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🔵",
    "info": "⚪",
}

# Caps on model-supplied fields (B7). One finding must not be able to
# consume the platform comment limit on its own, and a cap makes the
# progressive truncation in truncate_comment a fallback rather than the
# first line of defence.
_MAX_TITLE = 200
_MAX_DESCRIPTION = 4000
_MAX_SUGGESTION = 2000
_MAX_PATH = 400

# A mention that would notify a real person. Preceded by a non-word, so an
# email address local part does not qualify.
_MENTION = re.compile(r"(?<![\w`@.-])@([A-Za-z0-9][A-Za-z0-9-]{0,38})\b")

_WHITESPACE = re.compile(r"\s+")

# A URL the model emitted, including the scheme-less "www." form that
# GitHub autolinks on its own.
_URL = re.compile(
    r"(?i)\b(?:(?P<scheme>https?|ftp)://|(?P<www>www\.))"
    r"(?P<rest>[^\s<>`\]\)]*)",
)

# Renders identically, is not a link. Placed after the separator so the
# host stays readable to a person reading the comment.
_ZWSP = "\u200b"


def _defuse_link(match: re.Match[str]) -> str:
    """Break a URL so it renders as text rather than a link."""
    rest = match.group("rest")
    if match.group("scheme"):
        return f"{match.group('scheme')}:/{_ZWSP}/{rest}"
    return f"www.{_ZWSP}{rest}"


def _sanitise(text: str, limit: int) -> str:
    """Neutralise model-supplied text before it enters the comment (B7).

    The four prompt-injection layers all stop at the model boundary. This is
    the other end: prbot posts the model's words with pull-requests: write,
    so those words must not be able to open an HTML element, forge prbot's
    own state marker, or notify people.

    Escaping "<" is enough for all three. Markdown renders "&lt;" as a
    literal "<", so a finding that discusses <script> still reads correctly
    while being unable to open one.
    """
    if not text:
        return ""
    text = text[:limit]
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    # Backtick the handle rather than delete it: the reader still sees who
    # was named, and no notification fires.
    text = _MENTION.sub(r"`@\1`", text)
    # Break the link syntax itself rather than relying on a code span to
    # contain it (SEC-DATA-01). A code span is not containment: a stray
    # backtick anywhere in the model's text closes it, and GitHub autolinks
    # a bare "www." host that has no scheme to wrap in the first place.
    # A zero-width space after the scheme separator, or after "www.", leaves
    # the text readable and stops the autolinker recognising it.
    text = _URL.sub(_defuse_link, text)
    return text.replace("[", "&#91;").replace("]", "&#93;")


def _cell(text: str, limit: int) -> str:
    """Sanitise text for a markdown table cell.

    A pipe ends a cell and a newline ends a row, so either one from the
    model reshapes the table around it.
    """
    flattened = _WHITESPACE.sub(" ", text).strip()
    # The backslash is escaped FIRST. Escaping only the pipe leaves text
    # containing "\\|" as "\\\\|", and a table row is split on pipes before
    # inline parsing, where a backslash consumes the character after it: the
    # first backslash eats the second and the pipe splits the cell anyway
    # (SEC-DATA-02).
    return (
        _sanitise(flattened, limit)
        .replace("\\", "\\\\")
        .replace("|", "\\|")
    )


# Non-determinism disclaimer (S83)
_DISCLAIMER = (
    "_This review was generated by an AI model and may contain errors. "
    "Findings should be verified by a human reviewer._"
)


# Severity ordering for every list prbot renders. Findings are read in the
# order they have to be dealt with, so the index, the detail blocks and the
# truncation order all share one definition.
_SEVERITY_ORDER: dict[str, int] = {
    level: rank for rank, level in enumerate(SEVERITY_LEVELS)
}

# Dropped first when a comment will not fit (docs/review-output-template.md
# section 6.3). Detail about an issue nobody has to act on is the cheapest
# thing to lose.
_DROPPABLE_DETAIL = ("info", "low")


def _sorted_findings(findings: list[ScoredFinding]) -> list[ScoredFinding]:
    """Severity first, then confidence descending."""
    return sorted(
        findings,
        key=lambda sf: (
            _SEVERITY_ORDER.get(sf.finding.severity, 99),
            -sf.finding.confidence,
        ),
    )


def _format_issue_block(
    scored: ScoredFinding,
    *,
    marker: bool = False,
) -> str:
    """One issue in the shape every issue takes (template section 4).

    This is the body of the inline comment and, for a finding the diff cannot
    anchor, the body of its entry in the summary. Both come through here so
    that a reader meets one shape wherever a finding turns up and there is a
    single renderer to hold to the template.

    Header, Problem, Impact, Fix, marker. Impact and Fix are dropped rather
    than rendered empty: a label with nothing after it reads as prbot having
    lost the text, and every agent is required to supply an Impact, so an
    empty one is a prompt-compliance problem rather than a layout decision.
    """
    f = scored.finding
    # Two agents arriving at the same defect independently is evidence, and
    # after deduplication it is the only thing that distinguishes a merged
    # finding from a single-agent one (B1).
    agreement = (
        f" · reported by {len(f.reported_by)} agents"
        if len(f.reported_by) > 1
        else ""
    )

    parts = [
        f"**`{_cell(f.check_id, 64)}`** · {_cell(f.severity, 16)} · "
        f"{f.confidence}% confidence{agreement}",
        "",
        f"**Problem:** {_sanitise(f.description, _MAX_DESCRIPTION)}",
    ]
    if f.failure_scenario:
        parts += [
            "",
            f"**Impact:** {_sanitise(f.failure_scenario, _MAX_DESCRIPTION)}",
        ]
    if f.suggestion:
        parts += [
            "",
            f"**Fix:** {_sanitise(f.suggestion, _MAX_SUGGESTION)}",
        ]
    if marker:
        # C8: makes this thread recognisable on the next run, so the finding
        # is not posted twice and can be closed out when it goes away.
        # Invisible in rendered markdown.
        parts += ["", marker_for(finding_fingerprint(f))]

    return "\n".join(parts)


def format_review_comment(
    verdict: ReviewVerdict,
    score: ReviewScore,
    reported: list[ScoredFinding],
    borderline: list[ScoredFinding],
    hidden_count: int,
    outcomes: list[AgentOutcome],
    state_html: str = "",
    platform: Literal["github", "gitlab"] = "github",
    suppressed_count: int = 0,
    fixed_count: int = 0,
    *,
    unanchored: list[ScoredFinding] | None = None,
    inline_enabled: bool = False,
    produced_count: int = 0,
    dropped_count: int = 0,
) -> str:
    """Format the summary comment (G-28, S83, template section 5).

    With inline comments in play the summary indexes the issues and carries
    detail only for the findings that could not be anchored; without them it
    carries every issue in full, because there is nowhere else for that
    detail to go.

    Oversize comments are reduced by rebuilding with less in them rather than
    by cutting rendered markdown, so every attempt is a well-formed comment
    and each thing dropped is stated (template section 6.3).
    """
    has_results = any(isinstance(o, AgentResult) for o in outcomes)

    # G-28: Both agents failed
    if not has_results:
        return _format_review_incomplete(outcomes, state_html)

    # Detail belongs wherever the finding is not already being commented on.
    detailed = list(unanchored or []) if inline_enabled else list(reported)
    limit = _PLATFORM_LIMITS.get(platform, 65536)

    def build(
        shown_borderline: list[ScoredFinding],
        shown_detail: list[ScoredFinding],
    ) -> str:
        detail = _format_detail_section(
            shown_detail, inline_enabled=inline_enabled,
        )
        dropped = len(detailed) - len(shown_detail)
        if dropped:
            note = (
                f"_{dropped} low-severity issue detail(s) truncated for "
                f"size._"
            )
            detail = f"{detail}\n\n{note}" if detail else note

        collapsed = _format_borderline_section(shown_borderline)
        if borderline and not shown_borderline:
            collapsed = "_Borderline findings truncated for size._"

        sections = [
            _format_header(verdict, score),
            _format_counts(reported),
            _format_findings_table(
                reported,
                inline_enabled=inline_enabled,
                unanchored_count=len(detailed) if inline_enabled else 0,
            ),
            detail,
            collapsed,
            _format_agent_status(outcomes),
            _format_footer(
                hidden_count, state_html, suppressed_count, fixed_count,
                reconciliation=_format_reconciliation(
                    produced_count=produced_count,
                    merged_count=score.merged_count,
                    dropped_count=dropped_count,
                    suppressed_count=suppressed_count,
                    hidden_count=hidden_count,
                    borderline_count=len(borderline),
                    reported_count=len(reported),
                ),
            ),
        ]
        return "\n\n".join(s for s in sections if s)

    attempts = (
        (borderline, detailed),
        ([], detailed),
        (
            [],
            [
                sf for sf in detailed
                if sf.finding.severity not in _DROPPABLE_DETAIL
            ],
        ),
    )

    comment = ""
    for shown_borderline, shown_detail in attempts:
        comment = build(shown_borderline, shown_detail)
        if len(comment) <= limit:
            return comment

    return truncate_comment(comment, limit)


def _format_review_incomplete(
    outcomes: list[AgentOutcome],
    state_html: str,
) -> str:
    """Format body when both agents failed (G-28)."""
    lines = [
        "## ⚠️ Review Incomplete",
        "",
        "Both review agents encountered errors. "
        "No findings could be produced.",
        "",
    ]

    for outcome in outcomes:
        if isinstance(outcome, AgentError):
            lines.append(
                f"- **{outcome.agent}**: {_cell(outcome.error_type, 64)} · "
                f"{_cell(outcome.message, 400)}",
            )

    lines.extend([
        "",
        "---",
        _DISCLAIMER,
    ])

    if state_html:
        lines.extend(["", state_html])

    return "\n".join(lines)


def _format_header(verdict: ReviewVerdict, score: ReviewScore) -> str:
    """Format header with verdict badge and score."""
    badge = _VERDICT_BADGES.get(verdict.value, "")
    override = " _(critical override)_" if score.critical_override else ""
    return (
        f"## {badge} {verdict.value} · Score: "
        f"{score.clamped_score}/100{override}"
    )


def format_review_event_body(
    verdict: ReviewVerdict,
    score: ReviewScore,
    reported: list[ScoredFinding],
    inline_count: int,
) -> str:
    """The body of the platform review object (template section 5.2).

    A review cannot be found or rewritten by a later run, so the summary
    lives in its own comment and this carries only what the review itself
    has to say: the verdict, and how much was found. It is never empty,
    because GitHub rejects a REQUEST_CHANGES review with a blank body.
    """
    lines = [_format_header(verdict, score)]

    if not reported:
        lines.extend(["", "No issues found."])
        return "\n".join(lines)

    lines.extend(["", _format_counts(reported)])
    if inline_count:
        lines.extend([
            "",
            f"{inline_count} issue(s) commented on their lines. The full "
            "index is in prbot's summary comment.",
        ])
    else:
        lines.extend(["", "The full index is in prbot's summary comment."])
    return "\n".join(lines)


def _format_counts(reported: list[ScoredFinding]) -> str:
    """Severity tally, zero counts omitted (template section 5).

    The first thing a reader wants is the shape of the problem, and a count
    answers that before the table has to be read at all.
    """
    tally: dict[str, int] = {}
    for scored in reported:
        severity = scored.finding.severity
        tally[severity] = tally.get(severity, 0) + 1

    return " · ".join(
        f"{tally[level]} {level}"
        for level in SEVERITY_LEVELS
        if tally.get(level)
    )


def _format_findings_table(
    reported: list[ScoredFinding],
    *,
    inline_enabled: bool = False,
    unanchored_count: int = 0,
) -> str:
    """The index (template section 5). One row per issue, no detail.

    The description, impact and fix are deliberately absent: they are in the
    inline comment on the line the issue is about, and writing them twice is
    what made the old summary unreadable.
    """
    if not reported:
        return "No issues found."

    lines = [
        "### Issues",
        "",
        "| Severity | Check | Location | Confidence | Issue |",
        "|----------|-------|----------|------------|-------|",
    ]

    for scored in _sorted_findings(reported):
        f = scored.finding
        emoji = _SEVERITY_EMOJI.get(f.severity, "")
        location = _cell(
            f"{f.file_path}:{f.line_start}-{f.line_end}", _MAX_PATH,
        )
        lines.append(
            f"| {emoji} {f.severity} | `{_cell(f.check_id, 64)}` | "
            f"`{location}` | {f.confidence}% | "
            f"{_cell(f.title, _MAX_TITLE)} |",
        )

    if inline_enabled:
        # Say where the detail went, and admit the rows this does not cover
        # rather than claiming every issue has a thread.
        note = "Each issue above is commented on its line in the Files tab"
        if unanchored_count:
            note += f", except the {unanchored_count} listed below"
        lines.extend(["", f"{note}."])

    return "\n".join(lines)


def _format_detail_section(
    detailed: list[ScoredFinding],
    *,
    inline_enabled: bool,
) -> str:
    """Full issue blocks for findings with no thread of their own.

    Under review mode that is the findings the diff cannot anchor; in comment
    mode it is all of them. Either way this is the only copy of that detail,
    which is why it is here and not repeated beside the index.
    """
    if not detailed:
        return ""

    header = ""
    if inline_enabled:
        header = (
            f"### Not anchored to a line ({len(detailed)})\n\n"
            "These lines fall outside the diff, so they have no inline "
            "thread.\n\n"
        )

    return header + "\n\n".join(
        _format_issue_block(scored) for scored in _sorted_findings(detailed)
    )


def _format_borderline_section(
    borderline: list[ScoredFinding],
) -> str:
    """Format borderline findings in collapsed section.

    One line each, never a full block: these are below the reporting
    threshold and are shown so the reader can see what was weighed, not so
    they can be worked through.
    """
    if not borderline:
        return ""

    lines = [
        "<details>",
        f"<summary>Borderline findings ({len(borderline)})</summary>",
        "",
    ]

    for scored in _sorted_findings(borderline):
        f = scored.finding
        emoji = _SEVERITY_EMOJI.get(f.severity, "")
        location = _cell(
            f"{f.file_path}:{f.line_start}-{f.line_end}", _MAX_PATH,
        )
        lines.append(
            f"- {emoji} {f.severity} · `{_cell(f.check_id, 64)}` · "
            f"`{location}` · {f.confidence}% confidence · "
            f"{_cell(f.title, _MAX_TITLE)}",
        )

    lines.extend(["", "</details>"])
    return "\n".join(lines)


def _format_agent_status(outcomes: list[AgentOutcome]) -> str:
    """Format agent status, aggregated per agent (GEN-ARCH-01).

    A chunked review runs each agent once per chunk, so rendering one bullet
    per outcome showed the same agent several times with unlabelled numbers
    and nothing saying chunking had happened. Figures are summed per agent
    and the number of passes is stated when there was more than one.
    """
    order: list[str] = []
    stats: dict[str, dict[str, object]] = {}

    for outcome in outcomes:
        name = outcome.agent
        if name not in stats:
            order.append(name)
            stats[name] = {
                "passes": 0, "ok": 0, "findings": 0,
                "tokens": 0, "ms": 0, "errors": [],
            }
        s = stats[name]
        s["passes"] = int(s["passes"]) + 1
        if isinstance(outcome, AgentResult):
            s["ok"] = int(s["ok"]) + 1
            s["findings"] = int(s["findings"]) + len(outcome.findings)
            s["tokens"] = int(s["tokens"]) + (
                outcome.token_usage.input_tokens
                + outcome.token_usage.output_tokens
            )
            s["ms"] = int(s["ms"]) + outcome.latency_ms
        elif isinstance(outcome, AgentError):
            retry_note = " (retryable)" if outcome.retryable else ""
            errs = s["errors"]
            assert isinstance(errs, list)
            errs.append(
                f"{_cell(outcome.error_type, 64)}{retry_note} · "
                f"{_cell(outcome.message, 400)}",
            )

    lines = ["### Agent Status", ""]
    for name in order:
        s = stats[name]
        passes, ok = int(s["passes"]), int(s["ok"])
        errors = s["errors"]
        assert isinstance(errors, list)

        if ok == 0:
            # Every error, not just the first (GEN-ERR-02). Three chunks
            # failing three different ways is three different diagnoses, and
            # showing one of them hides the other two.
            lines.append(
                f"- **{name}**: ❌ no successful pass "
                f"({passes} attempted)",
            )
            for err in errors:
                lines.append(f"  - {err}")
            continue

        pass_note = f", {passes} passes" if passes > 1 else ""
        partial = f" ({ok} of {passes} passes succeeded)" if errors else ""
        lines.append(
            f"- **{name}**: {'✅' if not errors else '⚠️'} "
            f"{s['findings']} findings, {s['tokens']} tokens, "
            f"{s['ms']}ms{pass_note}{partial}",
        )
        for err in errors:
            lines.append(f"  - {err}")

    return "\n".join(lines)


def _format_reconciliation(
    *,
    produced_count: int,
    merged_count: int,
    dropped_count: int,
    suppressed_count: int,
    hidden_count: int,
    borderline_count: int,
    reported_count: int,
) -> str:
    """One line accounting for every finding the agents produced (D5).

    The comment used to have three silent sinks. De-duplication collapsed
    findings without saying so, the diff check deleted findings naming a
    file outside the diff to a log line nobody reads, and a suppression rule
    removed them quietly. A reader told in Agent Status that an agent
    produced four findings, and then shown three, had no way to learn what
    happened to the fourth, and no way to tell a filtered review from a
    clean one.

    Printed only when something was in fact lost between what the agents
    returned and what is on the page, so a clean review does not grow a line
    of accounting noise.
    """
    shown = reported_count + borderline_count
    lost = merged_count + dropped_count + suppressed_count + hidden_count
    if not lost or not produced_count:
        return ""

    parts = [f"{produced_count} produced"]
    if merged_count:
        parts.append(f"{merged_count} merged as one defect")
    if dropped_count:
        parts.append(f"{dropped_count} outside the diff")
    if suppressed_count:
        parts.append(f"{suppressed_count} suppressed by configuration")
    if hidden_count:
        parts.append(f"{hidden_count} hidden as low confidence")
    parts.append(f"{shown} shown")
    return f"_Findings: {' · '.join(parts)}._"


def _format_footer(
    hidden_count: int,
    state_html: str,
    suppressed_count: int = 0,
    fixed_count: int = 0,
    reconciliation: str = "",
) -> str:
    """Format footer with metadata, disclaimer, and state record."""
    lines = ["---"]

    if reconciliation:
        lines.append(reconciliation)
    elif hidden_count > 0:
        lines.append(
            f"_{hidden_count} low-confidence findings hidden._",
        )

    if suppressed_count > 0:
        # Always stated. A suppression list nobody can see stops being a
        # policy and becomes a gag (C4).
        lines.append(
            f"_{suppressed_count} finding(s) suppressed by "
            f"configuration._",
        )

    if fixed_count > 0:
        # C8: progress is worth stating. A review that only ever lists what
        # is wrong reads as a wall that never moves.
        lines.append(
            f"_{fixed_count} finding(s) resolved since the last review._",
        )

    lines.extend(["", _DISCLAIMER])

    if state_html:
        lines.extend(["", state_html])

    return "\n".join(lines)


def truncate_comment(comment: str, limit: int) -> str:
    """Last-resort hard cut, preserving the footer (template section 6.3).

    Progressive reduction happens in format_review_comment by rebuilding the
    comment with less in it, which always yields well-formed markdown. This
    is what remains when even the smallest well-formed comment does not fit,
    and its one job is to keep the disclaimer and the state record, without
    which the next run cannot find its own comment.
    """
    if len(comment) <= limit:
        return comment

    # The footer's own rule, which is the last one in the comment: model
    # prose is rendered above it, so the final match is always ours.
    footer_marker = comment.rfind("\n---\n")
    if footer_marker != -1:
        footer = comment[footer_marker:]
        available = limit - len(footer) - 40
        if available > 0:
            return (
                comment[:available]
                + "\n\n_...truncated for size..._"
                + footer
            )

    return comment[:limit]


def _anchor_line(
    finding: Finding,
    index: dict[str, set[int] | None],
) -> int | None:
    """The new-side line an inline comment on this finding can be posted to.

    None when the diff does not cover it: the platform would reject that
    position, or worse, silently move it.
    """
    covered = index.get(finding.file_path)
    if not covered:
        return None
    if finding.line_end not in covered:
        return None
    return finding.line_end


def build_inline_comments(
    reported: list[ScoredFinding],
    diff: PRDiff,
) -> list[InlineComment]:
    """Turn findings into comments anchored to the lines they are about (C1).

    Only findings that land on a line the diff actually covers become inline.
    Anything else is returned by unanchored_findings and carried in the
    summary, rather than being anchored to a line the platform would reject.
    """
    from prbot.security.validation import _build_line_index
    from prbot.vcs.diff_parser import map_new_to_old

    index = _build_line_index(diff)
    old_sides = {
        fd.path: map_new_to_old(fd.patch or "") for fd in diff.files
    }
    comments: list[InlineComment] = []

    for scored in reported:
        f = scored.finding
        line = _anchor_line(f, index)
        if line is None:
            continue

        covered = index[f.file_path]
        start = (
            f.line_start
            if covered and f.line_start in covered and f.line_start != line
            else None
        )
        comments.append(
            InlineComment(
                path=f.file_path,
                line=line,
                body=_format_issue_block(scored, marker=True),
                start_line=start,
                # None when the anchor is an added line, which is what a
                # platform that wants both sides has to be told apart.
                old_line=old_sides.get(f.file_path, {}).get(line),
            ),
        )

    return comments


def unanchored_findings(
    reported: list[ScoredFinding],
    diff: PRDiff,
) -> list[ScoredFinding]:
    """The findings no inline comment can be posted for (C1).

    The exact complement of build_inline_comments. The summary carries their
    detail in full, because there is no thread for it to live in, and a
    finding is never dropped for want of an anchor.
    """
    from prbot.security.validation import _build_line_index

    index = _build_line_index(diff)
    return [
        scored for scored in reported
        if _anchor_line(scored.finding, index) is None
    ]
