"""Markdown formatter for review comments (story-5-3).

Platform-specific formatting with verdict badges, findings tables,
collapsible borderline sections, and progressive truncation.
"""

from __future__ import annotations

import logging
from typing import Literal

from prbot.review.models import AgentError, AgentOutcome, AgentResult
from prbot.review.scorer import ReviewScore, ScoredFinding
from prbot.review.verdict import ReviewVerdict

logger = logging.getLogger(__name__)

# Platform comment size limits
_PLATFORM_LIMITS: dict[str, int] = {
    "github": 65536,
    "gitlab": 1_000_000,
}

# Verdict badges
_VERDICT_BADGES: dict[str, str] = {
    "APPROVE": "✅",
    "COMMENT": "💬",
    "REQUEST_CHANGES": "❌",
}

# Severity emoji for findings table
_SEVERITY_EMOJI: dict[str, str] = {
    "critical": "🔴",
    "high": "🟠",
    "medium": "🟡",
    "low": "🔵",
    "info": "⚪",
}

# Non-determinism disclaimer (S83)
_DISCLAIMER = (
    "_This review was generated by an AI model and may contain errors. "
    "Findings should be verified by a human reviewer._"
)


def format_review_comment(
    verdict: ReviewVerdict,
    score: ReviewScore,
    reported: list[ScoredFinding],
    borderline: list[ScoredFinding],
    hidden_count: int,
    outcomes: list[AgentOutcome],
    state_html: str = "",
    platform: Literal["github", "gitlab"] = "github",
) -> str:
    """Format the full review comment (G-28, S83).

    Handles both-agents-failed case with distinct body.
    """
    has_results = any(isinstance(o, AgentResult) for o in outcomes)

    # G-28: Both agents failed
    if not has_results:
        return _format_review_incomplete(outcomes, state_html)

    sections = [
        _format_header(verdict, score),
        _format_findings_table(reported),
        _format_borderline_section(borderline),
        _format_agent_status(outcomes),
        _format_footer(hidden_count, state_html),
    ]

    comment = "\n\n".join(s for s in sections if s)
    limit = _PLATFORM_LIMITS.get(platform, 65536)

    if len(comment) > limit:
        comment = truncate_comment(
            comment, limit, borderline, reported,
        )

    return comment


def _format_review_incomplete(
    outcomes: list[AgentOutcome],
    state_html: str,
) -> str:
    """Format body when both agents failed (G-28)."""
    lines = [
        "## ⚠️ Review Incomplete",
        "",
        "Both review agents encountered errors. "
        "No findings could be produced.",
        "",
    ]

    for outcome in outcomes:
        if isinstance(outcome, AgentError):
            lines.append(
                f"- **{outcome.agent}**: {outcome.error_type} — "
                f"{outcome.message}",
            )

    lines.extend([
        "",
        "---",
        _DISCLAIMER,
    ])

    if state_html:
        lines.extend(["", state_html])

    return "\n".join(lines)


def _format_header(verdict: ReviewVerdict, score: ReviewScore) -> str:
    """Format header with verdict badge and score."""
    badge = _VERDICT_BADGES.get(verdict.value, "")
    override = " _(critical override)_" if score.critical_override else ""
    return (
        f"## {badge} {verdict.value} — Score: "
        f"{score.clamped_score}/100{override}"
    )


def _format_findings_table(reported: list[ScoredFinding]) -> str:
    """Format findings table sorted by severity then confidence."""
    if not reported:
        return "_No findings to report._"

    severity_order = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
    sorted_findings = sorted(
        reported,
        key=lambda sf: (
            severity_order.get(sf.finding.severity, 99),
            -sf.finding.confidence,
        ),
    )

    lines = [
        "### Findings",
        "",
        "| Severity | Check | File | Lines | Confidence | Title |",
        "|----------|-------|------|-------|------------|-------|",
    ]

    for sf in sorted_findings:
        f = sf.finding
        emoji = _SEVERITY_EMOJI.get(f.severity, "")
        lines.append(
            f"| {emoji} {f.severity} | `{f.check_id}` | "
            f"`{f.file_path}` | {f.line_start}-{f.line_end} | "
            f"{f.confidence}% | {f.title} |",
        )

    # Add details for each finding
    lines.append("")
    for sf in sorted_findings:
        f = sf.finding
        lines.extend([
            f"#### `{f.check_id}`: {f.title}",
            "",
            f"**File:** `{f.file_path}` (L{f.line_start}-L{f.line_end})",
            "",
            f"{f.description}",
            "",
        ])
        if f.suggestion:
            lines.extend([
                f"**Suggestion:** {f.suggestion}",
                "",
            ])

    return "\n".join(lines)


def _format_borderline_section(
    borderline: list[ScoredFinding],
) -> str:
    """Format borderline findings in collapsed section."""
    if not borderline:
        return ""

    lines = [
        "<details>",
        f"<summary>Borderline findings ({len(borderline)})</summary>",
        "",
    ]

    for sf in borderline:
        f = sf.finding
        emoji = _SEVERITY_EMOJI.get(f.severity, "")
        lines.extend([
            f"- {emoji} **`{f.check_id}`**: {f.title} "
            f"(`{f.file_path}` L{f.line_start}-L{f.line_end}, "
            f"{f.confidence}% confidence)",
        ])

    lines.extend(["", "</details>"])
    return "\n".join(lines)


def _format_agent_status(outcomes: list[AgentOutcome]) -> str:
    """Format agent status section."""
    lines = ["### Agent Status", ""]

    for outcome in outcomes:
        if isinstance(outcome, AgentResult):
            findings_count = len(outcome.findings)
            tokens = outcome.token_usage
            lines.append(
                f"- **{outcome.agent}**: ✅ "
                f"{findings_count} findings, "
                f"{tokens.input_tokens + tokens.output_tokens} tokens, "
                f"{outcome.latency_ms}ms",
            )
        elif isinstance(outcome, AgentError):
            retry_note = " (retryable)" if outcome.retryable else ""
            lines.append(
                f"- **{outcome.agent}**: ❌ "
                f"{outcome.error_type}{retry_note} — {outcome.message}",
            )

    return "\n".join(lines)


def _format_footer(hidden_count: int, state_html: str) -> str:
    """Format footer with metadata, disclaimer, and state record."""
    lines = ["---"]

    if hidden_count > 0:
        lines.append(
            f"_{hidden_count} low-confidence findings hidden._",
        )

    lines.extend(["", _DISCLAIMER])

    if state_html:
        lines.extend(["", state_html])

    return "\n".join(lines)


def truncate_comment(
    comment: str,
    limit: int,
    borderline: list[ScoredFinding],
    reported: list[ScoredFinding],
) -> str:
    """Progressively truncate comment to fit platform limit (S17).

    Truncation order:
    1. Remove borderline section
    2. Remove low-severity finding details
    3. Truncate remaining content, preserving header and footer
    """
    # Step 1: Remove borderline section
    if "<details>" in comment and len(comment) > limit:
        start = comment.find("<details>")
        end = comment.find("</details>")
        if start != -1 and end != -1:
            comment = (
                comment[:start]
                + "_Borderline findings truncated for size._\n"
                + comment[end + len("</details>") :]
            )

    if len(comment) <= limit:
        return comment

    # Step 2: Remove low-severity details (info, low)
    for severity in ("info", "low"):
        for sf in reported:
            if sf.finding.severity == severity:
                detail_header = f"#### `{sf.finding.check_id}`: {sf.finding.title}"
                idx = comment.find(detail_header)
                if idx != -1:
                    next_header = comment.find("####", idx + 1)
                    next_section = comment.find("###", idx + 1)
                    end_pos = min(
                        p for p in (next_header, next_section, len(comment)) if p > idx
                    )
                    comment = comment[:idx] + comment[end_pos:]

        if len(comment) <= limit:
            return comment

    # Step 3: Hard truncate preserving footer
    footer_marker = comment.rfind("---")
    if footer_marker != -1:
        footer = comment[footer_marker:]
        available = limit - len(footer) - 50
        if available > 0:
            comment = (
                comment[:available]
                + "\n\n_...truncated for size..._\n\n"
                + footer
            )

    return comment[:limit]
